// IW5 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
	level.tweakfile = 1;
	maps\mp\_load::main();
	maps\mp\mp_rust_fx::main();
	maps\mp\_compass::setupminimap( "compass_map_mp_rust" );
	ambientplay( "ambient_mp_duststorm" );
	setdvar( "compassmaxrange", "1400" );
	game["attackers"] = "allies";
	game["defenders"] = "axis";
	maps\mp\_audio::add_reverb( "default", "quarry", 0.15, 0.9, 2 );

	// Pipe
	thread maps\mp\_utility::killTrigger( (1080, 1645, -156 - 30), 40, 30 );
	thread maps\mp\_utility::killTrigger( (1190, 1637, -154 - 50), 40, 30 );

	thread spawn_crates();
}

spawn_crates()
{
	// Orange truck
	spawn_collision( (-222, 65, -185), (0, -50, 0) );
	spawn_collision( (-282, 80, -185), (0, -130, 0) );
	spawn_collision( (-282, 80, -205), (0, -130, 0) );
	spawn_collision( (-275, 86, -185), (0, -130, 0) );
	spawn_collision( (-275, 86, -205), (0, -130, 0) );
	spawn_collision( (-165, 10, -182), (0, -40, 0) );

	// Ramp
	spawn_collision( (505, 305, -185), (-36, 90, 0) );
	spawn_collision( (522, 305, -185), (-36, 90, 0) );

	// Pipe
	spawn_collision( (1166, 1680, -190), (0, 0, 0) );
}

spawn_collision( pos, angles )
{
	while ( !isdefined( level.airdropcratecollision ) )
	{
		wait 0.05;
	}

	crate = spawn( "script_model", pos );
	crate.angles = angles;
	crate setmodel( "com_plasticcase_enemy" );
	crate clonebrushmodeltoscriptmodel( level.airdropcratecollision );
	crate hide();

/#
	crate show();
#/
}
